name: Auto Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,5,9 * * *'  

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config user.name "${{ vars.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "Auto commit at $(TZ=Asia/Jakarta date '+%Y-%m-%d %H:%M:%S')"
          git push
